name: Export maven coordinates
description: Gets maven coordinates from the pom.xml file

runs:
  using: "composite"
  steps:
    - id: export-pom-coordinates
      run: $GITHUB_ACTION_PATH/bash.sh
      shell: bash